# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-03 18:07
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='exec_datetime',
            field=models.DateTimeField(default=datetime.datetime(2017, 12, 3, 20, 7, 29, 875000), null=True),
        ),
    ]
